/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaswing;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author pedrogentil
 */
public class MinhaJanela extends javax.swing.JFrame {

    private double valor1 = 0, valor2 = 0, resultado = 0;
    private char operacao = ' ';

    /**
     * Creates new form MinhaJanela
     */
    public MinhaJanela() {
        initComponents();
        agruparBotoes();
        adicionarEventos();
    }


    private void agruparBotoes() {
        ButtonGroup grupoOperacoes = new ButtonGroup();
        grupoOperacoes.add(rdSoma);
        grupoOperacoes.add(rdSubtracao);
        grupoOperacoes.add(rdMultiplicacao);
        grupoOperacoes.add(rdDivisao);
    }

    private void adicionarEventos() {
        btOk.addActionListener(evt -> realizarCalculo());
        rdSoma.addActionListener(evt -> atualizarOperacao("+"));
        rdSubtracao.addActionListener(evt -> atualizarOperacao("-"));
        rdMultiplicacao.addActionListener(evt -> atualizarOperacao("*"));
        rdDivisao.addActionListener(evt -> atualizarOperacao("/"));
       
    }

    /**
     *
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        panelValores = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtPrimeiroValor = new javax.swing.JLabel();
        txtSegundoValor = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        panelTipo = new javax.swing.JPanel();
        txtTituloTipo = new javax.swing.JLabel();
        rdSoma = new javax.swing.JRadioButton();
        rdMultiplicacao = new javax.swing.JRadioButton();
        rdSubtracao = new javax.swing.JRadioButton();
        rdDivisao = new javax.swing.JRadioButton();
        btOk = new javax.swing.JButton();
        panelResultado = new javax.swing.JPanel();
        txtTituloResultado = new javax.swing.JLabel();
        txtValorResultado = new javax.swing.JTextField();

        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("jRadioButton1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Java");
        setBackground(new java.awt.Color(255, 255, 255));

        jInternalFrame2.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame2.setVisible(true);

        panelValores.setBackground(new java.awt.Color(255, 255, 255));
        panelValores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setText("Preencha os valores");

        txtPrimeiroValor.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimeiroValor.setText("Primeiro Valor");

        txtSegundoValor.setForeground(new java.awt.Color(0, 0, 0));
        txtSegundoValor.setText("Segundo Valor");

        txtValor1.setBackground(new java.awt.Color(153, 153, 153));
        txtValor1.setForeground(new java.awt.Color(0, 0, 0));
        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });

        txtValor2.setBackground(new java.awt.Color(153, 153, 153));
        txtValor2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelValoresLayout = new javax.swing.GroupLayout(panelValores);
        panelValores.setLayout(panelValoresLayout);
        panelValoresLayout.setHorizontalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValoresLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelValoresLayout.createSequentialGroup()
                        .addComponent(txtSegundoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelValoresLayout.createSequentialGroup()
                        .addComponent(txtPrimeiroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        panelValoresLayout.setVerticalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValoresLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimeiroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegundoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panelTipo.setBackground(new java.awt.Color(255, 255, 255));

        txtTituloTipo.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloTipo.setText("Escolha a operacao");

        rdSoma.setForeground(new java.awt.Color(0, 0, 0));
        rdSoma.setText("Soma");
        rdSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSomaActionPerformed(evt);
            }
        });

        rdMultiplicacao.setForeground(new java.awt.Color(0, 0, 0));
        rdMultiplicacao.setSelected(true);
        rdMultiplicacao.setText("Multiplicacao");
        rdMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMultiplicacaoActionPerformed(evt);
            }
        });

        rdSubtracao.setForeground(new java.awt.Color(0, 0, 0));
        rdSubtracao.setText("Subtracao");
        rdSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSubtracaoActionPerformed(evt);
            }
        });

        rdDivisao.setForeground(new java.awt.Color(0, 0, 0));
        rdDivisao.setText("Divisao");
        rdDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDivisaoActionPerformed(evt);
            }
        });

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTipoLayout = new javax.swing.GroupLayout(panelTipo);
        panelTipo.setLayout(panelTipoLayout);
        panelTipoLayout.setHorizontalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTituloTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTipoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdSoma)
                            .addComponent(rdMultiplicacao)
                            .addComponent(btOk))
                        .addGap(34, 34, 34)
                        .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdDivisao)
                            .addComponent(rdSubtracao))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panelTipoLayout.setVerticalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdSoma)
                    .addComponent(rdSubtracao))
                .addGap(18, 18, 18)
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMultiplicacao)
                    .addComponent(rdDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btOk)
                .addContainerGap())
        );

        panelResultado.setBackground(new java.awt.Color(255, 255, 255));

        txtTituloResultado.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloResultado.setText("Resultado");

        txtValorResultado.setBackground(new java.awt.Color(153, 153, 153));
        txtValorResultado.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTituloResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtValorResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(panelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void rdSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSomaActionPerformed
        operacao = '+';
        calcular();
    }//GEN-LAST:event_rdSomaActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void rdMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMultiplicacaoActionPerformed
        operacao = '*';
        calcular();
    }//GEN-LAST:event_rdMultiplicacaoActionPerformed

    private void rdSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSubtracaoActionPerformed
        operacao = '-';
        calcular();
    }//GEN-LAST:event_rdSubtracaoActionPerformed

    private void rdDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDivisaoActionPerformed
        operacao = '/';
        calcular();
    }//GEN-LAST:event_rdDivisaoActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        try {
            double valor1 = Double.parseDouble(txtValor1.getText());
            double valor2 = Double.parseDouble(txtValor2.getText());
            double resultado = 0;

            if (rdSoma.isSelected()) {
                resultado = valor1 + valor2;
            } else if (rdSubtracao.isSelected()) {
                resultado = valor1 - valor2;
            } else if (rdMultiplicacao.isSelected()) {
                resultado = valor1 * valor2;
            } else if (rdDivisao.isSelected()) {
                if (valor2 == 0) {
                    JOptionPane.showMessageDialog(this, "Erro: Divisão por zero!", "Erro",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                resultado = valor1 / valor2;
            } else {
                JOptionPane.showMessageDialog(this, "Selecione uma operação!", "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            txtValorResultado.setText(String.valueOf(resultado));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite números válidos!", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btOkActionPerformed

    private void atualizarValores() {
        try {
            valor1 = Double.parseDouble(txtValor1.getText());
            valor2 = Double.parseDouble(txtValor2.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite números válidos!", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void realizarCalculo() {
        try {
            double valor1 = Double.parseDouble(txtValor1.getText());
            double valor2 = Double.parseDouble(txtValor2.getText());
            double resultado = 0;

            if (rdSoma.isSelected()) {
                resultado = valor1 + valor2;
            } else if (rdSubtracao.isSelected()) {
                resultado = valor1 - valor2;
            } else if (rdMultiplicacao.isSelected()) {
                resultado = valor1 * valor2;
            } else if (rdDivisao.isSelected()) {
                if (valor2 == 0) {
                    JOptionPane.showMessageDialog(this, "Erro: Divisão por zero!", "Erro",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                resultado = valor1 / valor2;
            } else {
                JOptionPane.showMessageDialog(this, "Selecione uma operação!", "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            txtValorResultado.setText(String.valueOf(resultado));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite números válidos!", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void calcular() {
        atualizarValores(); // Atualiza os valores dos campos de texto

        switch (operacao) {
            case '+':
                resultado = valor1 + valor2;
                break;
            case '-':
                resultado = valor1 - valor2;
                break;
            case '*':
                resultado = valor1 * valor2;
                break;
            case '/':
                if (valor2 != 0) {
                    resultado = valor1 / valor2;
                } else {
                    JOptionPane.showMessageDialog(this, "Não é possível dividir por zero!", "Erro",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Selecione uma operação!", "Erro",
                        JOptionPane.WARNING_MESSAGE);
                return;
        }

        // Exibe o resultado em um campo de texto (ex: `txtResultado`)
        txtValorResultado.setText(String.valueOf(resultado));
    }

    private void atualizarOperacao(String operacao) {
        this.operacao = operacao.charAt(0); // Assume que a operação é um único caractere
        calcular();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhaJanela.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhaJanela.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhaJanela.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhaJanela.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> new MinhaJanela().setVisible(true));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinhaJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JPanel panelTipo;
    private javax.swing.JPanel panelValores;
    private javax.swing.JRadioButton rdDivisao;
    private javax.swing.JRadioButton rdMultiplicacao;
    private javax.swing.JRadioButton rdSoma;
    private javax.swing.JRadioButton rdSubtracao;
    private javax.swing.JLabel txtPrimeiroValor;
    private javax.swing.JLabel txtSegundoValor;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtTituloResultado;
    private javax.swing.JLabel txtTituloTipo;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    private javax.swing.JTextField txtValorResultado;
    // End of variables declaration//GEN-END:variables
}
